apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-predicitons
  labels:
    app: housing-predicitons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: housing-predicitons
  template:
    metadata:
      labels:
        app: housing-predicitons
    spec:
      containers:
        - name: housing-predicitons
          image: docker.io/volto/housing_prediction:latest
          ports:
            - containerPort: 80
              hostPort: 8080