apiVersion: v1
kind: Pod
metadata:
  name: housing-predicitons
  labels:
    app: housing-predicitons
spec:
  containers:
    - name: housing-predicitons
      image: volto/housing_prediction:v1.0.0
      ports:
        - containerPort: 80
          hostPort: 8080